name: tests
on:
  push:
  pull_request:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Set Python path
        run: |
          echo "PYTHONPATH=$PWD:$PWD/src:$PYTHONPATH" >> $GITHUB_ENV
      - name: Run tests
        run: pytest -q
